apiVersion: v1                          # Specifies API version as v1 for PersistentVolumeClaim
kind: PersistentVolumeClaim              # Defines the resource type as PersistentVolumeClaim
metadata:
  name: efs-dynamic                      # Sets the name of the PersistentVolumeClaim as "efs-dynamic"
spec:
  storageClassName: "efs-expense"        # Uses the StorageClass named "efs-expense" for provisioning
  accessModes:
    - ReadWriteMany                      # Allows multiple nodes to read and write to the volume
  resources:
    requests:
      storage: 3Gi                       # Requests 3Gi of storage for this PersistentVolumeClaim
---
apiVersion: v1                           # Specifies API version as v1 for Pod
kind: Pod                                # Defines the resource type as Pod
metadata:
  name: efs-dynamic                      # Sets the name of the Pod as "efs-dynamic"
  labels:
    purpose: efs-dynamic                 # Adds a label "purpose: efs-dynamic" for Pod selection
spec:
  containers:
  - name: nginx                          # Defines a container named "nginx"
    image: nginx                         # Uses the nginx image for this container
    volumeMounts:                        # Specifies volume mounts for the container
    - name: efs-dynamic                  # Mounts the volume named "efs-dynamic"
      mountPath: /usr/share/nginx/html   # Mounts the volume at /usr/share/nginx/html in the container
  volumes:
  - name: efs-dynamic                    # Defines a volume named "efs-dynamic"
    persistentVolumeClaim:
      claimName: efs-dynamic             # Links to the PersistentVolumeClaim named "efs-dynamic"
---
kind: Service                            # Defines the resource type as Service
apiVersion: v1                           # Specifies API version as v1 for Service
metadata:
  name: nginx                            # Sets the name of the Service as "nginx"
spec:
  type: LoadBalancer                     # Sets the Service type as LoadBalancer for external access
  selector:
    purpose: efs-dynamic                 # Selects Pods labeled with "purpose: efs-dynamic" to expose
  ports:
  - name: nginx-svc-port                 # Names the port configuration as "nginx-svc-port"
    protocol: TCP                        # Specifies the protocol as TCP
    port: 80                             # Sets the Service port to 80
    targetPort: 80                       # Routes the Service port 80 to the container's port 80
    nodePort: 30007                      # Assigns node port 30007 for external access to the Service
