# Pods - Pods are the smallest deployable units of computing that you can create and manage in Kubernetes.
# A Pod (as in a pod of whales or pea pod) is a group of one or more containers, with shared storage and network resources, and a specification for how to run the containers.


# apiVersion: v1
# kind: Pod
# metadata:
#   name: nginx    # name of the pod 
# spec:
#   containers:
#   # docker run -d --name nginx nginx
#   - name: nginx
#     image: nginx


apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  # docker run -d --name nginx nginx
  - name: nginx
    image: nginx:stable-perl