# nodeport - The NodePort service serves as the external entry point for incoming requests for your app. The assigned NodePort is publicly exposed in the kubeproxy settings of each worker node in the cluster.

kind: Service                     # Defines the resource type as Service
apiVersion: v1                    # Specifies the API version (v1) for the Service resource
metadata:                         # Metadata information about the Service
  name: nginx-np                  # Sets the name of the Service to "nginx-np"
spec:                             # Details the specifications for the Service
  type: NodePort                  # Defines the Service type as NodePort, exposing it on each Node's IP
  selector:                       # Defines the label selector to match Pods for this Service
    project: expense              # Matches Pods with the label "project: expense"
    module: backend               # Matches Pods with the label "module: backend"
    environment: dev              # Matches Pods with the label "environment: dev"
  ports:                          # Specifies the list of ports exposed by the Service
  - name: nginx-svc-port          # Names the port for easy reference as "nginx-svc-port"
    protocol: TCP                 # Uses TCP as the protocol for communication
    port: 80                      # Sets the Service's external port to 80
    targetPort: 80                # Directs traffic to port 80 on the container running inside the matched Pods
